name: culhwch

services:
  front:
    container_name: culhwch-front
    depends_on:
      api:
        condition: service_healthy
    restart: always
    image: ghcr.io/kamchatskiy/culhwch-front:latest
    networks:
      - culhwch
    ports:
      - 8893:80

  api:
    container_name: culhwch-api
    depends_on:
      db:
        condition: service_healthy
    restart: always
    image: ghcr.io/kamchatskiy/culhwch-api:latest
    command: python app.py
    environment:
      DB_HOST: db
      POSTGRES_DB: culhwch
      POSTGRES_USER: culhwch
      POSTGRES_PASSWORD: ${PASSWORD}
      SERVER_PASSWORD: ${PASSWORD}
    networks:
      - culhwch
    expose:
      - 3000
    volumes:
      - ${PROJECT_DIR}/culwch/protocols:/app/protocols:ro
      - ${PROJECT_DIR}/culwch/validators:/app/validators:ro
    healthcheck:
      test: curl --fail http://localhost:3000/api/healthcheck || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  db:
    container_name: culhwch-db
    restart: always
    image: postgres:15.1-alpine
    environment:
      POSTGRES_USER: culhwch
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_DB: culhwch
    networks:
      culhwch:
        aliases:
          - postgres
          - db
    expose:
      - 5432
    volumes:
      - /${DATA_DIR}/culhwch/db:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U culhwch -d culhwch
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  culhwch:
