name: Docker images CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: set up docker buildx
        uses: docker/setup-buildx-action@v3

      - name: ghcr login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build frontend
        uses: docker/build-push-action@v6
        with:
          context: server
          file: server/docker/front/Dockerfile
          push: true
          tags: ${{ github.repository_owner }}/culhwch-front:latest

      - name: build api
        uses: docker/build-push-action@v6
        with:
          context: server
          file: server/docker/api/Dockerfile
          push: true
          tags: ${{ github.repository_owner }}/culhwch-api:latest
