name: Docker images CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: set up docker buildx
        uses: docker/setup-buildx-action@v1

      - name: ghcr login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build frontend
        uses: docker/build-push-action@v2
        with:
          context: ./server
          file: ./docker/front/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/culhwch-front:latest

      - name: build api
        uses: docker/build-push-action@v2
        with:
          context: ./server
          file: ./docker/api/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/culhwch-api:latest
